replicaCount: 1

image:
  repository: 068712669296.dkr.ecr.us-east-1.amazonaws.com/petclinic/spring-petclinic
  tag: "12"
  pullPolicy: Always
imagePullSecrets:
  - name: ecr-secret

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx

  host: petclinic.local

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"
